# https://pre-commit.com/#adding-pre-commit-plugins-to-your-project

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.4"
    hooks:
      - id: flake8
